server:
  port: 8080

spring:
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exam_system?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zw.entity

logging:
  level:
    com.zw: debug
    org.springframework.security: debug
    root: INFO
    com.zw.mapper: DEBUG
    com.baomidou.mybatisplus: DEBUG

jwt:
  secret-key: examSystem
  ttl: 24h
  token-name: authentication
  refresh-token:
    ttl: 24h
    token-name: refresh_token

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# Swagger 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.zw.controller

# 阿里云OSS配置 自行配置
aliyun:
  oss:
    endpoint: oss-cn-beijing.aliyuncs.com
    accessKeyId: ${ALIYUN_ACCESS_KEY_ID}
    accessKeySecret: ${ALIYUN_ACCESS_KEY_SECRET}
    bucketName: exam-system
    domain: https://${ALIYUN_ACCESS_KEY_ID}.${ALIYUN_OSS_ENDPOINT}/

# 本地文件上传配置
file:
  upload:
    local-path: D:/file
